image: archlinux
packages:
  - hut
  - wayland
  - wayland-protocols
  - fcft
  - pixman
  - libpulse
sources:
  - https://git.sr.ht/~andreafeletto/levee
secrets:
  - 8a791f75-2c57-4cd6-8cae-710da7d992cc
tasks:
  - zig: |
      curl -O https://ziglang.org/download/0.10.0/zig-linux-x86_64-0.10.0.tar.xz
      tar xf zig-linux-x86_64-0.10.0.tar.xz
      mv zig-linux-x86_64-0.10.0 zig
  - submodules: |
      cd levee
      git submodule update --init
  - package: |
      cd levee
      ./contrib/package || exit 0
      hut git artifact upload *.tar.gz
  - build: |
      cd levee
      ~/zig/zig build
